### ISSUE TITLE
how to cite?

### ISSUE THREAD

**Issue by t-silvers** [broadinstitute/pyqtl#2]
Thanks for porting a lot of useful functions scattered across R packages! How would you like users to cite this package?

**Comment by francois-a** [comment]
Hi,
Thanks, I'm glad this is useful! A large part of the code in this repo was developed for GTEx. If you use this package in GTEx-related analyses, you could cite the [2020 paper](https://science.sciencemag.org/content/369/6509/1318.abstract). Otherwise just citing this repo should be fine.
