### ISSUE TITLE
Numpy errors

### ISSUE THREAD

**Issue by liqingbioinfo** [broadinstitute/pyqtl#5]
To whom it may concern:
    
     I applied quantile normalization function "qtl.norm.normalize_quantiles()" to my gene expression data but encountered the following errors. Can you please let me know what to do to solve the problem? 
     Thank you very much. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liq17/.conda/envs/polyfun/lib/python3.8/site-packages/qtl/norm.py", line 35, in normalize_quantiles
    dupes = np.zeros(m, dtype=np.int)
  File "/home/liq17/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by francois-a** [comment]
Thanks for reporting this, fixed in 6102de7f2112c17e4444c49f6181265690b5746b.
