### ISSUE TITLE
how to make bed file from gtf file

### ISSUE THREAD

**Issue by liaguiro** [broadinstitute/pyqtl#7]
How can I use pyqtl to make a bed file from a GTF file? Tensorqtl says we can use the function io.gtf_to_tss_bed, but there isn't much guidance on how to run it after installing pyqtl.

Thanks,

**Comment by francois-a** [comment]
The purpose of `io.gtf_to_tss_bed` is to make a BED file with TSS coordinates only, see for example [here](https://github.com/broadinstitute/gtex-pipeline/blob/6983de2e5e6c7fdfe689bc797e8d6b62468bc1d1/qtl/src/eqtl_prepare_expression.py#L109).

If you want to convert a GTF file to BED more generally, you can use
```
annot = qtl.annotation.Annotation("annotation.gtf")
annot.write_bed("annotation.bed")
```
