### ISSUE TITLE
Source Code for IntervalTree

### ISSUE THREAD

**Issue by majgah** [broadinstitute/pyqtl#8]
In the annotation file, there is the following import;
from bx.intervals.intersection import IntervalTree
However, I can't find its source code from the [bx-python](https://github.com/bxlab/bx-python/tree/main) GitHub repository. Is there any package version available?

**Comment by francois-a** [comment]
It's in that repo: https://github.com/bxlab/bx-python/blob/main/lib/bx/intervals/intersection.pyx#L325

**Comment by majgah** [comment]
Thank you for the reference. It seems there is an issue with the package installation that skips the .pyx file.
